# Generated by Django 4.2.3 on 2023-10-03 18:09

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default=core.models.default_imagen_producto, upload_to='productos/'),
        ),
    ]
