# Generated by Django 4.2.3 on 2023-10-08 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_comuna_region_factura_telefono_ordencompra_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordencompra',
            name='comuna',
        ),
        migrations.DeleteModel(
            name='Factura',
        ),
        migrations.DeleteModel(
            name='OrdenCompra',
        ),
    ]
