# Generated by Django 4.1.8 on 2023-11-20 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_customuser_apellido_customuser_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
