# Generated by Django 4.1.8 on 2023-11-20 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_ordencompra_valor_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordencompra',
            name='valor_total',
        ),
    ]
